name: Build TWRP

on:
  push:
    branches:
      - main  # Cambia a la rama que estés usando
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Usa la versión más reciente de actions/checkout

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3

      - name: Initialize repo
        run: |
          mkdir twrp
          cd twrp
          curl -o repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod +x repo
          ./repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          ./repo sync -j$(nproc --all)

      - name: Build TWRP
        run: |
          cd twrp
          source build/envsetup.sh
          lunch twrp_X70-eng  # Cambia "twrp_X70" por el nombre de tu dispositivo
          mka vendorbootimage -j$(nproc --all)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Usa la versión más reciente
        with:
          name: twrp-image
          path: twrp/out/target/product/X70/vendor_boot.img  # Cambia "X70" por el nombre de tu dispositivo
